# Generated by Django 5.2 on 2025-05-11 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('doc_ci', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now_add=True)),
                ('agg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attendance', models.DateField(auto_now_add=True)),
                ('doc_ci', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci_student', to='at_system.students')),
            ],
        ),
    ]
