# Generated by Django 5.2 on 2025-05-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='doc_ci',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
