# Generated by Django 5.2 on 2025-05-13 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_system', '0002_alter_students_doc_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='date_birthdate',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='fecha_nacimiento'),
            preserve_default=False,
        ),
    ]
