# Generated by Django 5.2 on 2025-05-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_system', '0003_students_date_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fistname',
            new_name='firstname',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_attendance',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
